openapi: 3.0.1
info:
  title: Environmental indicators API
  description: Indicators used to track the national environmental objectives, for more
    info see <a
    href="http://www.sverigesmiljomal.se/environmental-objectives/">The
    environmental objectives system</a>.
  version: v1.0
  contact:
    email: data@nv.se
    name: Support
  license:
    name: Creative Commons Zero, CC0
    url: https://creativecommons.org/publicdomain/zero/1.0/
servers:
  - url: https://indikatorer-api.naturvardsverket.se/
paths:
  /api/v1/indicators:
    get:
      tags:
        - Indicators
      operationId: indicators
      summary: Full list of indicators
      description: The full list of indicators (limited datasets content). Use this to get
        the the full presentations (using the parameter 'includePresentations').
      parameters:
        - name: includePresentations
          in: query
          schema:
            type: boolean
          description: Whether to include presentations or not
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Indicator"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Indicator"
        "401":
          description: Unauthorized
          content: {}
        "500":
          description: InternalServerError
          content: {}
  "/api/v1/indicators/{id}":
    get:
      tags:
        - Indicators
      operationId: indicator
      summary: A single indicator
      description: A single indicator (excluding presentations). Use this to get the full
        datasets content.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
          description: Use the "Key"-property value retrieved from the /indicators endpoint
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Indicator"
            text/json:
              schema:
                $ref: "#/components/schemas/Indicator"
            application/xml:
              schema:
                $ref: "#/components/schemas/Indicator"
            text/xml:
              schema:
                $ref: "#/components/schemas/Indicator"
        "400":
          description: BadRequest
          content: {}
        "401":
          description: Unauthorized
          content: {}
        "500":
          description: InternalServerError
          content: {}
components:
  schemas:
    Indicator:
      type: object
      properties:
        Id:
          type: integer
          format: int32
          description: Internal identifier
        Key:
          type: integer
          format: int32
          description: External identifier, use this to filter
        Name:
          type: string
          description: Indicator name
        ShortName:
          type: string
          description: Indicator name shorter version
        IngressText:
          type: string
          description: Introductory description
        IsOfficialStatistics:
          type: boolean
          description: Related to the Swedish offical statistics
        Status:
          type: string
          description: Always "Published"
        DataSupplier:
          type: string
          description: Name of party supplying the data for the indicator
        DataSupplierUrl:
          type: string
          description: URL for data supplier
        Contact:
          type: string
          description: Contact person name for the indicator
        ContactEmail:
          type: string
          description: Contact person email for the indicator
        Responsible:
          type: string
          description: Organisation or person responsible for the indicator
        ResponsibleOrganizationId:
          type: string
          description: Identifier for organisation responsible for the indicator
        ResponsibleOrganizationName:
          type: string
          description: Organisation responsible for the indicator
        ResponsibleOrganizationUrl:
          type: string
          description: URL for organisation responsible for the indicator
        LastChanged:
          type: string
          format: date-time
          description: Indicator last update date
        MainObjective:
          $ref: "#/components/schemas/Objective"
        SecondaryObjectives:
          type: array
          items:
            $ref: "#/components/schemas/Objective"
        DPSIR:
          type: array
          items:
            type: string
          description: Type of the indicator according to the <a
            href="https://en.wikipedia.org/wiki/DPSIR">DPSIR</a> classification.
        Presentations:
          type: array
          items:
            $ref: "#/components/schemas/Presentation"
        DataSets:
          type: array
          items:
            $ref: "#/components/schemas/DataSet"
    Objective:
      type: object
      properties:
        Name:
          type: string
        Id:
          type: integer
          format: int32
        Type:
          type: string
      description: a <a
        href="http://www.sverigesmiljomal.se/environmental-objectives/">National
        environmental quality objective</a>
    Presentation:
      type: object
      description: Selected data and text that describes a certain development. The
        presentations represent the analytical part of the indicator.
      properties:
        Name:
          type: string
          description: Name of presentation
        Responsible:
          type: string
          description: Organisation or person responsible
        ResponsibleEmail:
          type: string
          description: Email for responsible entity
        Location:
          type: string
          description: Geographical coverage of the presentation
        LocationId:
          type: string
          description: Identifier for the geographical location
        Level:
          type: integer
          format: int32
          description: Hierarchy of geographical locations (e.g. 1=National, 2=county...)
        IndicatorText:
          type: string
          description: Description of the presentation
        ImmersiveText:
          type: string
          description: A more in-depth description of the presentation
        MethodText:
          type: string
          description: Description of the method used for the presentation
        LocalizedTexts:
          type: array
          items:
            $ref: "#/components/schemas/LocalizedText"
        DataSetIds:
          type: array
          items:
            type: integer
            format: int32
          description: Identifiers for the DataSets used in the presentation
    DataSet:
      type: object
      description: Represents data for a certain location and phenomenon
      properties:
        Id:
          type: integer
          format: int32
          description: System internal identifier for the dataset
        ExternalId:
          type: integer
          format: int32
          description: Identifier for the dataset
        Name:
          type: string
          description: Describes the dataset
        Unit:
          type: string
          description: Unit of measurment for the values in the dataset
        LocationType:
          type: string
          description: Indentifier of the location type
        LocationTypeDisplayName:
          type: string
          description: Name of the location type (e.g. country or county)
        LocationId:
          type: string
          description: Identifier for the location
        Responsible:
          type: string
          description: Organisation or person responsible
        ResponsibleEmail:
          type: string
          description: Email for responsible entity
        Locations:
          type: array
          items:
            $ref: "#/components/schemas/Location"
        VisualizationTypes:
          type: array
          items:
            $ref: "#/components/schemas/VisualizationType"
    LocalizedText:
      type: object
      description: Local variants of the presentation texts (e.g. for each county)
      properties:
        Location:
          type: string
          description: Name of geographical location
        LocationId:
          type: string
          description: Identifier for location
        IaCode:
          type: string
          description: Internal identifier
        IndicatorText:
          type: string
          description: Description of the presentation
        ImmersiveText:
          type: string
          description: A more in-depth description of the presentation
        MethodText:
          type: string
          description: Description of the method used for the presentation
    Location:
      type: object
      description: Describes a geographical coverage
      properties:
        Name:
          type: string
          description: Name of location
        Id:
          type: string
          description: Identifier for location
        PresentationVariables:
          type: array
          items:
            $ref: "#/components/schemas/PresentationVariable"
    VisualizationType:
      type: object
      description: Internal type information
      properties:
        Type:
          type: string
    PresentationVariable:
      type: object
      description: Data for a certain phenomenon
      properties:
        Id:
          type: integer
          format: int32
          description: Internal identifier for presentationvariable
        Name:
          type: string
          description: Name of presentationvariable
        ViewInVis:
          type: boolean
          description: Internal flag
        ExternalId:
          type: integer
          format: int32
          description: Identifier for presentationvariable
        DataSeries:
          type: array
          items:
            $ref: "#/components/schemas/DataPoint"
    DataPoint:
      type: object
      description: Label-value pair data structure
      properties:
        Label:
          type: string
          description: Label for value
        Value:
          type: number
          format: float
          description: Data value
